### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by RathalM** [samuraitruong/chess.com-daily-puzzle#2]
as the example command "npm start 10" , giving error and I don't know how to fix, please replay, thanks

> chess.com-daily-puzzle@1.0.0 start
> node index.mjs "10"

file:///home/user/chess.com-daily-puzzle-main/job/index.mjs:14
    if (r.response?.data?.message === "End date must be after start date")
                   ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Comment by samuraitruong** [comment]
I think that is your node version, can you check what is your note version? better try with 18 or 20 that fully support module
